services:
  - type: web
    name: hotel-reservation-backend
    env: node
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: postgresql://root:C5Y9znB3LNHx27Q5MYwMt4QW5eJjzG40@dpg-d5g9i9ffte5s73fg0jcg-a.oregon-postgres.render.com/hotel_reservation_db_fbjp
      - key: PG_SSL
        value: true
      - key: JWT_SECRET
        value: hotel_secret_2024_rutvik_!@#$%
      - key: JWT_EXPIRE
        value: 7d
      - key: FRONTEND_URL
        value: https://hotel-reservation-system-avvn.onrender.com
      - key: MAX_ROOMS_PER_BOOKING
        value: 5
      - key: MIN_STAY_NIGHTS
        value: 1
    healthCheckPath: /api/health
    autoDeploy: true